[build]
  command = "npm run build:netlify"
  publish = "dist/cv_cherkas.ivan_full_stack_developer/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[context.develop.environment]
  NODE_VERSION = "20"
